# Generated by Django 3.0.3 on 2020-02-20 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('O-', 'O Negative'), ('O+', 'O Positive'), ('A-', 'A Negative'), ('A+', 'A Positive'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=3)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('SC', 'SC'), ('CC', 'CC')], max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('marital_status', models.CharField(choices=[('MA', 'Married'), ('SG', 'Single'), ('DV', 'Divorced')], max_length=2)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('physically_challenged', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('has_hiv', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('has_malaria', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('hypertensive', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('diabetic', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
